//import "oaidl.idl";
//import "ocidl.idl";
//

// IDLTesting.idl
namespace IDLTesting
{  
    [default_interface]
    runtimeclass LiteWatcher
    {
        LiteWatcher();

        Windows.Foundation.Collections.IObservableVector<Object> KnownDevices{ get; };
        
        Boolean BikeConnected();
        Boolean BikeUpdated();
        Int16 BikePower();

        void EnumerateButton_Click();
        Boolean SubscribeToPowerData(String Id);
        Boolean UnSubscribeToPowerData();
    }

    /// <summary>
    ///     Display class used to represent a BluetoothLEDevice in the Device list
    /// </summary>
    runtimeclass BluetoothLEDeviceDisplay
    {
        Windows.Devices.Enumeration.DeviceInformation DeviceInformation{ get; };

        String Id{ get; };
        String Name{ get; };
        Boolean IsPaired{ get; };
        Boolean IsConnected{ get; };
        Boolean IsConnectable{ get; };

        IMapView<String, Object> Properties{ get; };

        void Update(Windows.Devices.Enumeration.DeviceInformationUpdate deviceInfoUpdate);
    };
}